{{- if $.Values.createCertificate }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: '{{ .Values.urlSafeCertificateName }}'
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: Certificate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  commonName: '{{ .Values.domainName}}'
  dnsNames:
    - '{{ .Values.domainName}}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: '{{ .Values.urlSafeCertificateName }}'
{{- end }}
